# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: survey_rails_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: survey_rails_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: survey-rails_database_production
  username: survey-rails_app
  password: <%= ENV['SURVEY-RAILS_DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000